[ { title: 'INF 132',
    description: 'Students undertake significant projects in the elicitation and specification of HCI requirements and the thorough evaluation of user interfaces.  SEE CATALOGUE FOR PREREQUISITES.',
    instructor: 'Alfred Kobsa' },
  { title: 'INF 143',
    description: 'Introduction to interactive visual interfaces for large datasets, and to principles of human visual perception and human computer interaction that inform their design. Various applications for data analysis and monitoring are discussed. SEE CATALOGUE FOR PREREQUISITES.',
    instructor: 'Gary Olson' },
  { title: 'INF 148',
    description: 'Introduction to ubiquitous computing research methods, tools, and techniques. Prototyping, design, and evaluation of physical computing applications, smart environments, embedded systems, and future computing scenarios. Includes hands-on in-class laboratory exercises.  SEE CATALOGUE FOR PREREQUISITES.',
    instructor: 'Darren A. Denenberg' },
  { title: 'INF 153',
    description: 'Introduces concepts and principles of collaborative systems. Topics may include shared workspaces, group interaction, workflow, architectures, interaction between social and technical features of group work, and examples of collaborative systems used in real-world settings. Students develop a simple collaborative application. SEE CATALOGUE FOR PREREQUISITES.',
    instructor: 'Kathleen Hammond Pine' },
  { title: 'INF 163',
    description: 'Students undertake projects intended to gather and analyze data from situations in which computers are used, organize and conduct experiments intended to test hypotheses about impacts, and explore the application of concepts learned in previous courses. SEE CATALOGUE FOR PREREQUISITES.',
    instructor: 'Matthew J. Bietz' },
  { title: 'INF 191B',
    description: 'Group supervised project in which students analyze, specify, design, construct, evaluate, and adapt a significant information processing system. Topics include team management, professional ethics, and systems analysis. Prerequisites for 191A: Informatics 121, 131, 151; either Informatics 161 as a prerequisite or Informatics 123 as a corequisite; and upper-division standing; for 191B: Informatics 191A; for 191C: Informatics 191B. In-progress grading for 191B only.',
    instructor: 'Darren A. Denenberg' } ]
